name: Release Trace Blame CI

on:
  push:
    branches: [ master ]
  release:
    types: [created]
  workflow_run:
    workflows: [ "flake_and_test" ]
    branches: [ master ]
    types:
      - completed

jobs:
  release_to_pypi:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release to PyPi
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel
          pip install setuptools
      - name: Build wheels
        run: |
          python3 setup/setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
